### ISSUE TITLE
Need a bin() equivalent of hex(), oct() and dec()

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#10]
It's important to be able to print the bit representation of values in memory; at the very least for integer-typed values.

The library should therefore have a `strf::bin()`, and `int_format_fn` should have a `bin()` member.

PS - It's true that this doesn't exist in the standard library, but it's only for historical reasons (see also [this discussion](https://stackoverflow.com/questions/41359232/has-there-been-a-proposal-to-add-stdbin-to-the-c-standard)).

**Comment by robhz786** [comment]
Implemented on branch develop.

**Comment by eyalroz** [comment]
I don't see `bin()` in the listing of formatting functions here:

https://robhz786.github.io/strf/doc/quick_reference.html#format_functions

**Comment by robhz786** [comment]
That's because the docs refers to the master branch.
I didn't merge develop into master yet.

**Comment by robhz786** [comment]
Merge to master now. And updated docs:
https://robhz786.github.io/strf/doc/quick_reference.html#_integers

**Comment by robhz786** [comment]
Merged to master and updated docs now.

**Comment by robhz786** [comment]
Updated.
