### ISSUE TITLE
Two templates for strf::range coincide

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#12]
If I try to use:
```
strf::range<const char*>(some_const_char_ptr, another_const_char_ptr)
```
I get the error:
```
error: more than one instance of overloaded function "strf::range" matches the argument list:
            function template "auto strf::range(ForwardIt, ForwardIt)"
            function template "auto strf::range(const Range &, const CharT *)"
            argument types are: (util::constexpr_string::const_iterator, util::constexpr_string::const_iterator)
```
I guess somehow the second template parameter is inferred.

Right now I'm using
```
strf::range_p<const char *>{some_const_char_ptr, another_const_char_ptr}
```
as a workaround, but I shouldn't have to do that.

What could be done is the following:
```
- inline STRF_HD auto range(const Range& range, const CharT* sep)
+ inline STRF_HD auto range(const typename std::enable_if<not std::is_pointer<typename std::remove_cv<Range>::type>::value, Range &>::type range, const CharT* sep)
```

**Comment by robhz786** [comment]
The use of `std::enable_if` is a nice solution, but we still need to fix the ambiguity of when the range is an array of chars.
```
char arr[] = "abcd";
strf::to(stdout) (strf::range(arr, arr + 3)); // I want to print "abc"
strf::to(stdout) (strf::range(arr, ", "));    // I want to print "a, b, c, d".
```
There is no way the differentiate the two cases above. So I think the only good solution is to rename `range` ( possibly to `range_sep`) for the cases that take the separator.

**Comment by eyalroz** [comment]
Wait, why not call it a `separated_range`?

**Comment by robhz786** [comment]
Well, I like short names

**Comment by eyalroz** [comment]
@robhz786 : But that name suggests a different meaning. A `range_sep` seems to be a "range separator". And that's if the reader has figured out what `sep` stands for, which isn't always the case.

**Comment by robhz786** [comment]
Okay, I will change it to `separated_range`

**Comment by eyalroz** [comment]
@robhz786 : You also have corresponding names such as `sep_range_p` (from before this change) and `fmt_range_sep` which you need to consider. I wonder what `sep_range_p` is...

**Comment by robhz786** [comment]
I renamed `fmt_range_sep` to `fmt_separated_range`.
I will rename `sep_range_p` to `separated_range_p`.
