### ISSUE TITLE
fmt() fails on the GPU

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#17]
Consider the `write_within_kernel` unit test, and specifically, the `kernel_using_cstr_to()` kernel in which it's easy to demonstrate this issue. Its code is:
```
__global__ void kernel_using_cstr_to(char* buffer, std::size_t buffer_size)
{
	int global_thread_id = threadIdx.x + blockIdx.x * blockDim.x;
	auto printer = strf::to(buffer, buffer_size);
	printer ( "Hello", ' ', "world, from thread ", global_thread_id );
}
```
This makes extremely limited use of the capabilities of `strf`, and perhaps we were hasty in not testing more functionality. Specifically, even the following small addition is problematic:
```
	printer ( strf::fmt(threadIdx.x) );
```
This produces a bunch of warnings; and when running the thing, we get a launch failure. (*edit*: Need to establish exactly why.)

**Comment by robhz786** [comment]
Could you test my solution on branch hotfix-0.10.3 ?  If it works, I will merge it to master.

**Comment by eyalroz** [comment]
I will, but for now - have a look at my new branch for fixing the warnings (which doesn't fix the main issue).

**Comment by eyalroz** [comment]
Ah... it looks like you were a bit more adventurous than me. I was assuming I can't return a null reference from `get_default()`... are you sure that's not used anywhere?

Anyway - it works. But - replace `__CUDACC__` with `__CUDA_ARCH__`, otherwise you're making the host-side version also return nullptr.

**Comment by robhz786** [comment]
That null reference shouldn't be a problem for now. But if you ever have a problem, there is another workaround you can do. Replace:
```
    auto printer = strf::to(buffer, buffer_size);
```
by 
```
    auto my_facets = strf::pack
        ( strf::default_numpunct<2>(), strf::default_numpunct<8>()
        , strf::default_numpunct<10>(), strf::default_numpunct<16>() );
    auto printer = strf::to(buffer, buffer_size).with(my_facets);
```
It will prevent `numpunct_c<Base>::get_default` to be called.
Actually, I just realized that `strf::pack` also doesn't compile on cuda due to some missing `STRF_HD`. But I will fix that do.

**Comment by eyalroz** [comment]
Perhaps you could mention this secondary workaround in a comment in code?

Also, this is a part of your library where I haven't pressured you into adopting more intuitive names as opposed to "numpunct", and more documentation about facets.

**Comment by robhz786** [comment]
I borrowed the name from `std::numpunct`, which I think people are most familiar with.
The documentation is indeed lacking. I must agree. But I expect it will be much better in the next release since I'm working on it right now.

**Comment by eyalroz** [comment]
BTW, I'm still getting some weirdness with printing to my stringstream/printfing ostream, but that is still all probably my own bugs. If not, I'll open another one...
