### ISSUE TITLE
strf should warn you when using 0 as a fill character

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#19]
I've just resolved this bug which was due to me saying:
```
fmt(my_number).fill(0)
```
when in fact I should have written
```
fmt(my_number).fill('0')
```
I wonder if it wouldn't be a good idea for `strf` to warn me somehow that I'm using the NUL character as a fill value.

**Comment by robhz786** [comment]
I have no idea how that could be implemented. But I will think about.

**Comment by fwsGonzo** [comment]
I think I just had the same problem, but instead it's a 64-bit float that is zero. It ends up writing \0 using strf::format()

**Comment by eyalroz** [comment]
@robhz786 : Well, could arrange it so that non-character integers have their own overload, which static-asserts false. 

Also, you could perhaps consider preventing this from happening altogether by dynamically checking the fill value to not be zero.

**Comment by robhz786** [comment]
> Well, could arrange it so that non-character integers have their own overload, which static-asserts false.
Yes, that's certainly possible. But in this case, we would get an error instead of a warning. If that's fine with you, it is fine with me.

> Also, you could perhaps consider preventing this from happening altogether by dynamically checking the fill value to not be zero.
In this case, we need to decide what the library should do when it is zero. Typically, strf prints a replacement character when there is something wrong ( U'\uFFFD' or '?' ). But in this case, maybe it could instead print the zero digit '0'.

**Comment by eyalroz** [comment]
> Yes, that's certainly possible. But in this case, we would get an error instead of a warning. If that's fine with you, it is fine with me.

It is fine by me. If somebody wants something else, let them file an issue :-)  No need to cater to unrealistic and purely theoretical use-cases.

**Comment by robhz786** [comment]
The proposed solution is on master branch now, but I'm not satisfied. I've been thinking that if people are using '0' as the fill character then perhaps something else should change in the library.

What I now think that should actually be done is to add two new format functions for integer and floating points:
- `operator~` : same effect as the ' ' in `printf`: insert a space before non-negative numbers
- `zeros(unsigned sub_width)` or just `z(unsigned sub_width)`: insert '0' before the digits and after the sign or base indication such that the total number of non-fill character is not smaller than `sub_width`

Examples:

    assert(strf::to_string(~fmt(123))      == " 123");
    assert(strf::to_string( fmt(123).z(6)) == "000123");
    assert(strf::to_string(fmt(-123).z(6)) == "-00123");
    assert(strf::to_string(~fmt(123).z(6)) == " 00123");
    assert(strf::to_string(+fmt(123).z(6)) == "+00123");
    assert(strf::to_string(~fmt(1.5).z(6)) == " 001.5");

Note that the argument passed to `z` function is independent from the witdh passsed to the alignment function:

    assert(strf::to_string(~fmt(123) < 10)      == " 123      ");
    assert(strf::to_string( fmt(123).z(6) < 10) == "000123    ");
    assert(strf::to_string(fmt(-123).z(6) < 10) == "-00123    ");
    assert(strf::to_string(~fmt(123).z(6) < 10) == " 00123    ");
    assert(strf::to_string(+fmt(123).z(6) < 10) == "+00123    ");
    assert(strf::to_string(+fmt(1.5).z(6) ^ 10) == "  +001.5  ");

After that, I think I should remove the `p(unsigned)` option for integers and `operator%` for all types.

Do you find this a good idea ?

**Comment by robhz786** [comment]
No, I think this solution I just proposed is not ideal either. I will think more about it and maybe reopen this issue later, or maybe open another one.

**Comment by eyalroz** [comment]
Just had a look at this. Well, I don't like super-short identifiers like `z`. I also don't like non-intuitive operator overloads, like `~`. It's enough that we need to memorize C string formatting codes, and C++ stream manipulator names, and in C++20 also `std::format` codes... so the less you add to that, the better.

**Comment by robhz786** [comment]
Instead of creating `z`, perhaps we could change the meaning of `operator%`?
    
    assert(strf::to_string(+fmt(1) % 6) == "+00001");
    assert(strf::to_string(*hex(1) % 6) == "0x0001");

So `operator%` would almost continue to do what it does today, except that:

- It would always imply the fill is `'0'`
- It could only be used for numeric types.
- NaN and infinite floating-point values would not be prefixed by zeros. 

Do you have any idea of what could we use instead of `operator~`?  Maybe a `space()` member function?

**Comment by eyalroz** [comment]
I'd rather see something which says "fill" or  "pad" or "width" etc.

**Comment by robhz786** [comment]
Created issue #29 to deal with this matter.
