### ISSUE TITLE
Variable set but not used in utf8_to_utf32_size()

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#2]
In the function `utf8_to_utf32_size()`, in `utf_encodings.hpp`, [there is](https://github.com/robhz786/strf/blob/8cbd600fe18f3777bf45b0e0f80430c5b8f191e0/include/strf/detail/utf_encodings.hpp#L289) a variable that gets set but isn't used.

There are a few other instances of the same issue, e.g. in `utf16_sanitize_size()`.

**Comment by robhz786** [comment]
Fixed on develop. 
https://github.com/robhz786/strf/commit/ca7de61d62d34b187be5a650f364619c158876a1

**Comment by eyalroz** [comment]
I think those are not the only two functions. Look for instances of `ch2 = `.
