### ISSUE TITLE
unsigned char printing behavior different from std::cout

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#25]
If you print an unsigned char using a `cstr_writer`, you'll get the number printed; if you stream that value to `std::cout`, you'll get the character with that ASCII value.

I get this in a CUDA kernel, but it's probably the same in host-side code.

**Comment by robhz786** [comment]
I checked that `fmtlib`  does as `strf`. It seems that it became this way at https://github.com/fmtlib/fmt/issues/217 , when a user complained that `std::uint8_t` was printed as `char` ( `std::uint8_t` is defined as `unsigned char` in many ( if not all ) compilers ).

I think it makes more sense to print `unsigned char` ( as well as `signed char`, which is used to `std::int8_t` ) as integers, despite `std::cout` doing differently.

**Comment by eyalroz** [comment]
I don't particularly mind. In that case, the host-side streaming into `expected` for the new testcase I introduced just needs to be altered.

Although... maybe a better possibility is for this to be controlled by a CMake option, or a preprocessor define, or even a template parameter/constructor parameter.
