### ISSUE TITLE
Re-list version 0.10.4

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#27]
Hello @robhz786  :-)

My last release of cuda-kat requires  v0.10.4 of strf, or later on the 0.10 line. But - 0.10.4 was removed (I think; it _was_ released, right?)

Now, I'll update the code to be compatible with a newer version, but please keep 0.10.4 up on the versions page so that people can actually use my existing release.

**Comment by robhz786** [comment]
Sorry about that. I don't know what happened.
Anyway, just pushed tags v0.10.4 and v0.10.5.
