### ISSUE TITLE
"parameter pack was references but not expanded" in printers_tuple.hpp

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#3]
When compiling `printers_tuple.hpp` with NVCC, I get the following errors:
```
detail/printers_tuple.hpp(50): error: parameter pack "I" was referenced but not expanded
detail/printers_tuple.hpp(50): error: parameter pack "T" was referenced but not expanded
detail/printers_tuple.hpp(50): error: parameter pack "args" was referenced but not expanded
detail/printers_tuple.hpp(50): error: expected a "{"
detail/printers_tuple.hpp(151): error: parameter pack "I" was referenced but not expanded
detail/printers_tuple.hpp(151): error: parameter pack "Printers" was referenced but not expanded
detail/printers_tuple.hpp(152): error: expected a "{"
```
And indeed, it does seem you're using unexpanded parameter packs. Bug?

**Comment by eyalroz** [comment]
It seems the code is C++14, where apparently you can expand multiple packs at once (and also - have an `auto` return type without a `-> some_type_here` at the end of the declaration).

If you force CUDA to use C++14 when compiling, then these are gone. But I would rather not force that. How difficult would it be for you to m ake this printers_tuple work with C++11?

**Comment by robhz786** [comment]
Strf targets C++14. There are many parts that are not conformant to C++, not only printers_tuple.

**Comment by eyalroz** [comment]
@robhz786 : Well, it turns out it's not a C++11-vs-C++14 after all.

**Comment by robhz786** [comment]
It is used in two things:
- joins:
   https://robhz786.github.io/strf/doc/quick_reference.html#_joins

- applying facets to a sub-set of arguments:
  https://robhz786.github.io/strf/doc/quick_reference.html#_facets

`detail/printers_tuple.hpp` is errouneosly included in `destination.hpp`.
I will remove that `#include` since `destination.hpp` does not use `printers_tuple`.

**Comment by eyalroz** [comment]
@robhz786 : But `write_args.hpp` is  in `printers_tuple.hpp`... you would need to move it out of there, as it is used in `destination.hpp`.

**Comment by robhz786** [comment]
Could test if the following would fix the issue:

```
--- a/include/strf/detail/printers_tuple.hpp
+++ b/include/strf/detail/printers_tuple.hpp
@@ -45,7 +45,7 @@ public:
 
     template <typename ... Args>
     constexpr explicit simple_tuple_impl(simple_tuple_from_args, Args&& ... args)
-        : detail::indexed_obj<I, T>{args}...
+        : detail::indexed_obj<I, T>(args)...
     {
     }
 
@@ -147,7 +147,7 @@ public:
         , Preview& p
         , const strf::detail::simple_tuple<Args...>& args )
         : indexed_obj<I, Printers>
-        { make_printer<CharT>(strf::rank<5>{}, fp, p, args.template get<I>()) } ...
+        ( make_printer<CharT>(strf::rank<5>(), fp, p, args.template get<I>()) ) ...
     {
     }

```

**Comment by eyalroz** [comment]
Well, you should drop the `detail::`, anyways, since this class is within detail. But checking.

**Comment by eyalroz** [comment]
The idea works, but you've missed a few () <-> {} cases. Please check out my fork's feature/cuda branch in a couple of minutes.

**Comment by robhz786** [comment]
> @robhz786 : But `write_args.hpp` is in `printers_tuple.hpp`... you would need to move it out of there, as it is used in `destination.hpp`.

I thinking about moving `write_args` to `printers.hpp`.

**Comment by robhz786** [comment]
[Fixed](https://github.com/robhz786/strf/commit/4a31a01b92db8052c0728d7f0305a9b496895b18)
Some extra changes were necessary to avoid compile errors and run-time errors when using GCC.

**Comment by robhz786** [comment]
[Fixed](https://github.com/robhz786/strf/commit/4a31a01b92db8052c0728d7f0305a9b496895b18). 
Some extra changes were necessary to avoid compile errors and run-time errors when using GCC.

**Comment by eyalroz** [comment]
@robhz786 : Should I introduce these on my feature branch as well? Or shall we wait for the merge?

**Comment by robhz786** [comment]
I created a PR in your repository to sync these changes. You just need to merge it.
https://github.com/eyalroz/strf/pull/6
