### ISSUE TITLE
Possible floating point presentation error on RISC-V

### ISSUE THREAD

**Issue by fwsGonzo** [robhz786/strf#41]
```
>>> [gameplay1] says: assertion k >= cache_holder<FloatFormat>::min_k && k <= cache_holder<FloatFormat>::max_k failed: "/home/gonzo/github/rvscript/programs/micro/ext/strf/include/strf/detail/dragonbox.hpp", line 2337, function: static constexpr typename strf::detail::jkj::dragonbox::detail::cache_holder<FloatFormat>::cache_entry_type strf::detail::jkj::dragonbox::detail::policy_impl::cache::full::get_cache(int) [with FloatFormat = strf::detail::jkj::dragonbox::ieee754_binary32; typename strf::detail::jkj::dragonbox
[0] 0x0000000000123e78 + 0x014: syscall(long)
```

I've spent some time on this and I cannot explain it. Every other formatting library can print floats, although I do realize that va_arg promotes to double. So, from what I remember printing 1.0f works, but everything else ends up as 8e-47 and so on.

I am willing and able to debug it further, but I was doing something else when the presentation issue .. presented itself. It's probably important to mention that I am running this in a custom RISC-V emulator, which means it is possible that I am emulating something wrongly. I haven't seen any wrong emulation happen in several months, so I am hoping that maybe this problem is related to something else?

The only significant change happening lately is changing from RISC-V GCC 9.x to 11.x.

Any ideas?

**Comment by robhz786** [comment]
I'm not sure I will be able to reproduce this. I'm not very familiar with cross-compilation and emulation

Anyway, since this assertion failure happens in dragonbox.hpp, which is an adaptation from https://github.com/jk-jeon/dragonbox,  could you check whether the original works?

Perhaps could you try to run the example https://github.com/jk-jeon/dragonbox#usage-examples?

**Comment by fwsGonzo** [comment]
I finally found the problem after much investigation, and as is tradition it was my own doing: https://github.com/fwsGonzo/libriscv/commit/a9ef39550ba43929fa02127886a3d5c76c9fe6d5

Sorry for the false alarm! Everything works as it should.

**Comment by robhz786** [comment]
No problem! I'm glad it's not an strf's bug.
