### ISSUE TITLE
Consider more renaming for clarity

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#6]
If `cv()` is now `convert_encoding()`, it probably makes sense to rename `sani()` into `sanitize()`...

Also - doesn't `cv_string` now need to be `converted_encoding_string` ?

More renaming ideas:

* `underlying_outbuf::pos()`, `outbuf::pos()` etc. - very confusing! Readers will tend to assume this method returns a _numeric value_. But - I don't have a great idea for an alternative name... `at_current_pos()`/`at_current_position()` ? Hmm.
*  `outbuf` -> `output_buffer` - these days, I think `streambuf` would not have made it past the language standard committee...

**Comment by eyalroz** [comment]
The documentation still says `cv()` and `sani()`.

**Comment by eyalroz** [comment]
... and, actually, some places in the code still use `sani()` or `cv()`. [Example](https://github.com/robhz786/strf/search?q=sani%28&unscoped_q=sani%28).

**Comment by robhz786** [comment]
`sani` still exits, but it is an alias to `sanitize_encoding` or `sanitize_from_encoding`.
`cv` renamed to `conv`, which is an alias to `convert_encoding` or `convert_from_encoding`.
`outbuf` renamed to `outbuff`.
`outbuf::pos` renamed to `outbuff::pointer`.
