### ISSUE TITLE
Member names - consider not starting with an underscore

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#9]
In C++, it is forbidden to use identifiers having two consecutive underscores, or beginning with an underscore and a capital letter. Your use of underscore+lowercase letter is valid, but it's customarily avoided and [many recommend against it](https://stackoverflow.com/q/228783/1593077). I'd consider placing the extra underscore at the _end_, i.e. `my_class::_foo` becomes `my_class::_foo::foo_`.

**Comment by robhz786** [comment]
Fixed on develop. Now private names use an underscore at the end.
